/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'agent-api': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'agent.task.execute'; data: never }>
    'result-logger': EventHandler<never, never>
    'health-check': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'master-agent': EventHandler<never, { topic: 'agent.task.completed'; data: never }>
  }
    
}