/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'taskResult': MotiaStream<{ taskId: string; task: string; sessionId?: string; app?: string; success: boolean; status: 'completed' | 'failed' | 'awaiting_clarification' | 'timeout'; output?: string; error?: string; executionTime?: number; structuredOutput?: unknown; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; skillNames?: Array<string>; conversationLength?: number; executionCount?: number; data?: unknown }; artifacts?: Array<{ id: string; type: 'video' | 'code' | 'infographic' | 'table' | 'audio' | 'text' | 'image'; action: 'generated' | 'uploaded' | 'created'; path: string; description?: string; metadata?: unknown; timestamp: string }>; pinned?: boolean; timestamp: string }>
    'taskExecution': MotiaStream<{ taskId: string; task: string; status: 'pending' | 'started' | 'running' | 'completed' | 'failed' | 'awaiting_clarification'; output?: string; error?: string; currentStep?: string; executionTime?: number; sessionId?: string; timestamp: string; type: 'task' | 'skill' | 'agent' | 'agent_created' | 'agent_acquired' | 'agent_status' | 'intent_analysis' | 'ptc_planning' | 'awaiting_clarification'; skill?: string; stage?: 'pre' | 'processing' | 'post'; progressType?: 'step' | 'heartbeat' | 'status' | 'chat'; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; data?: unknown } }>
    'executionTraces': MotiaStream<{ traceId: string; level: 'task' | 'agent' | 'skill' | 'tool-call' | 'agent-internal' | 'skill-internal'; taskId: string; agentId?: string; skillName?: string; parentTraceId?: string; stage: 'pre' | 'processing' | 'post' | 'intent_analysis' | 'ptc_planning' | 'llm_call' | 'skill_generation'; purpose?: string; status: 'started' | 'running' | 'completed' | 'failed' | 'retried'; inputData?: string; outputData?: string; error?: string; errorStack?: string; retryCount: number; maxRetries: number; executionTime?: number; timestamp: string; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; sessionId?: string; data?: unknown; llmProvider?: string; llmModel?: string; llmRequest?: { messages?: Array<{ role: string; content: string }>; maxTokens?: number; temperature?: number }; llmResponse?: { content?: string; promptTokens?: number; completionTokens?: number; totalTokens?: number } } }>
  }

  interface Handlers {
    'media-serve-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'token-usage-writer': EventHandler<{ traceId: string; taskId: string; agentId?: string; skillName?: string; model: string; provider: string; promptTokens: unknown; completionTokens: unknown; totalTokens: unknown; timestamp: string }, never>
    'token-usage-extractor': EventHandler<{ traceId: string; level: 'task' | 'agent' | 'skill' | 'tool-call' | 'agent-internal' | 'skill-internal'; taskId: string; agentId?: string; skillName?: string; parentTraceId?: string; stage: 'pre' | 'processing' | 'post' | 'intent_analysis' | 'ptc_planning' | 'llm_call' | 'skill_generation'; purpose?: string; status: 'started' | 'running' | 'completed' | 'failed' | 'retried'; inputData?: string; outputData?: string; error?: string; errorStack?: string; retryCount: number; maxRetries: number; executionTime?: number; timestamp: string; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; sessionId?: string; data?: unknown; llmProvider?: string; llmModel?: string; llmRequest?: { messages?: Array<{ role: string; content: string }>; maxTokens?: number; temperature?: number }; llmResponse?: { content?: string; promptTokens?: number; completionTokens?: number; totalTokens?: number } } }, { topic: 'token_usage_recorded'; data: { traceId: string; taskId: string; agentId?: string; skillName?: string; model: string; provider: string; promptTokens: unknown; completionTokens: unknown; totalTokens: unknown; timestamp: string } }>
    'output-history-tracker': EventHandler<never, never>
    'notify-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'health-check': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserProfileAnalysis': CronHandler<never>
    'SoulPeriodicCheck': CronHandler<{ topic: 'soul.agent.execute'; data: never }>
    'soul-cleanup-cron': CronHandler<never>
    'workspace-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'workflows-list-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'workflow-detail-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'traces-submit-api': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'execution.trace.created'; data: { traceId: string; level: 'task' | 'agent' | 'skill' | 'tool-call' | 'agent-internal' | 'skill-internal'; taskId: string; agentId?: string; skillName?: string; parentTraceId?: string; stage: 'pre' | 'processing' | 'post' | 'intent_analysis' | 'ptc_planning' | 'llm_call' | 'skill_generation'; purpose?: string; status: 'started' | 'running' | 'completed' | 'failed' | 'retried'; inputData?: string; outputData?: string; error?: string; errorStack?: string; retryCount: number; maxRetries: number; executionTime?: number; timestamp: string; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; sessionId?: string; data?: unknown; llmProvider?: string; llmModel?: string; llmRequest?: { messages?: Array<{ role: string; content: string }>; maxTokens?: number; temperature?: number }; llmResponse?: { content?: string; promptTokens?: number; completionTokens?: number; totalTokens?: number } } } }>
    'execution-traces-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'token-usage-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'tasks-unpin-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'tasks-pinned-list-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'tasks-pin-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'task-token-usage-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'task-ptc-code-api': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: Array<{ round: number; code: string; selectedSkills: Array<string>; reasoning?: string; timestamp: number }> }> | ApiResponse<404, { success: boolean; message: string }> | ApiResponse<500, { success: boolean; message: string; error?: string }>, never>
    'task-hitl-result-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'task-chat-api': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'agent.task.execute'; data: never }>
    'system-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'stream-history-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'soul-session-stop': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'soul-session-delete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'soul-initialize': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'soul-execution-history': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'soul-config': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'soul-execute': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'agent.task.completed'; data: never } | { topic: 'agent.task.failed'; data: never } | { topic: 'execution.trace.created'; data: { traceId: string; level: 'task' | 'agent' | 'skill' | 'tool-call' | 'agent-internal' | 'skill-internal'; taskId: string; agentId?: string; skillName?: string; parentTraceId?: string; stage: 'pre' | 'processing' | 'post' | 'intent_analysis' | 'ptc_planning' | 'llm_call' | 'skill_generation'; purpose?: string; status: 'started' | 'running' | 'completed' | 'failed' | 'retried'; inputData?: string; outputData?: string; error?: string; errorStack?: string; retryCount: number; maxRetries: number; executionTime?: number; timestamp: string; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; sessionId?: string; data?: unknown; llmProvider?: string; llmModel?: string; llmRequest?: { messages?: Array<{ role: string; content: string }>; maxTokens?: number; temperature?: number }; llmResponse?: { content?: string; promptTokens?: number; completionTokens?: number; totalTokens?: number } } } }>
    'soul-agents-status': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'skills-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'skill-details-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'knowledge-table-schema-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'knowledge-collections-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'get-user': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'get-user-sessions': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'get-session': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'favorites-remove-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'favorites-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'favorites-add-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'context-tool-usage-api': ApiRouteHandler<{ taskId: string; toolName: string; success: boolean; timestamp: string; summary: string; error?: string }, ApiResponse<200, { success: boolean }> | ApiResponse<400, { error: string; details?: Array<unknown> }> | ApiResponse<500, { error: string }>, never>
    'context-skill-execution-api': ApiRouteHandler<{ taskId: string; skillName: string; success: boolean; startedAt: string; completedAt: string; duration: number; inputSummary: string; outputType?: string; scenario?: string; error?: string }, ApiResponse<200, { success: boolean }> | ApiResponse<400, { error: string; details?: Array<unknown> }> | ApiResponse<500, { error: string }>, never>
    'context-outputs-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'context-failure-experience-api': ApiRouteHandler<{ taskId: string; skillName: string; error: string; scenario: string; solution: string; timestamp: string }, ApiResponse<200, { success: boolean }> | ApiResponse<400, { error: string; details?: Array<unknown> }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'context-compression-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'context-artifacts-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'context-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'apps-list-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'app-knowledge-collections-update-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'app-knowledge-collections-remove-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'app-knowledge-collections-batch-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'app-knowledge-collections-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'app-knowledge-collections-add-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'subagents-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'task-result-handler': EventHandler<never, never>
    'soul-agent-executor': EventHandler<never, { topic: 'agent.task.completed'; data: never } | { topic: 'agent.task.failed'; data: never } | { topic: 'execution.trace.created'; data: { traceId: string; level: 'task' | 'agent' | 'skill' | 'tool-call' | 'agent-internal' | 'skill-internal'; taskId: string; agentId?: string; skillName?: string; parentTraceId?: string; stage: 'pre' | 'processing' | 'post' | 'intent_analysis' | 'ptc_planning' | 'llm_call' | 'skill_generation'; purpose?: string; status: 'started' | 'running' | 'completed' | 'failed' | 'retried'; inputData?: string; outputData?: string; error?: string; errorStack?: string; retryCount: number; maxRetries: number; executionTime?: number; timestamp: string; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; sessionId?: string; data?: unknown; llmProvider?: string; llmModel?: string; llmRequest?: { messages?: Array<{ role: string; content: string }>; maxTokens?: number; temperature?: number }; llmResponse?: { content?: string; promptTokens?: number; completionTokens?: number; totalTokens?: number } } } }>
    'master-agent': EventHandler<never, { topic: 'agent.task.completed'; data: never } | { topic: 'agent.task.failed'; data: never } | { topic: 'execution.trace.created'; data: { traceId: string; level: 'task' | 'agent' | 'skill' | 'tool-call' | 'agent-internal' | 'skill-internal'; taskId: string; agentId?: string; skillName?: string; parentTraceId?: string; stage: 'pre' | 'processing' | 'post' | 'intent_analysis' | 'ptc_planning' | 'llm_call' | 'skill_generation'; purpose?: string; status: 'started' | 'running' | 'completed' | 'failed' | 'retried'; inputData?: string; outputData?: string; error?: string; errorStack?: string; retryCount: number; maxRetries: number; executionTime?: number; timestamp: string; metadata?: { llmCalls?: number; skillCalls?: number; totalTokens?: number; sessionId?: string; data?: unknown; llmProvider?: string; llmModel?: string; llmRequest?: { messages?: Array<{ role: string; content: string }>; maxTokens?: number; temperature?: number }; llmResponse?: { content?: string; promptTokens?: number; completionTokens?: number; totalTokens?: number } } } }>
    'failure-handler': EventHandler<never, never>
    'agent-tasks-delete-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'agent-results-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'agent-result-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'agent-retry-api': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'agent.task.execute'; data: never }>
    'agent-api': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'agent.task.execute'; data: never }>
  }
    
}